#!/bin/bash

set -xue

CASSANDRA_VERSION=$1
STANDARD_CASSANDRA=true

STANDARD_URL=http://dl.bintray.com/apache/cassandra/pool/main/c/cassandra

CASSANDRA_DEB=$(mktemp apache-cassandra.deb.XXXXXX)
CASSANDRA_TOOLS_DEB=$(mktemp cassandra-tools.deb.XXXXXX)

if [[ $# -eq 2 && $2 == 'y' ]] ; then
    STANDARD_CASSANDRA=false
    CASSANDRA_DEB="/tmp/cassandra.deb"
    CASSANDRA_TOOLS_DEB="/tmp/cassandra-tools.deb"
else
    CASSANDRA_DOWNLOAD="curl -L ${STANDARD_URL}/cassandra_${CASSANDRA_VERSION}_all.deb > ${CASSANDRA_DEB};"
    CASSANDRA_TOOLS_DOWNLOAD="curl http://dl.bintray.com/apache/cassandra/pool/main/c/cassandra/cassandra-tools_${CASSANDRA_VERSION}_all.deb > ${CASSANDRA_TOOLS_DEB}"
fi

if ${STANDARD_CASSANDRA}; then
    eval ${CASSANDRA_DOWNLOAD}
    eval ${CASSANDRA_TOOLS_DOWNLOAD}
fi

dpkg --force-depends -i ${CASSANDRA_DEB}
APT_GET_OPTS=-f dagi

rm ${CASSANDRA_DEB}

# FILE=/usr/sbin/cassandra; sed -re 's/(\s+)exec \$NUMACTL/\1exec -a cassandra \$NUMACTL/' "${FILE}" > "${FILE}.tmp"; chmod --reference="${FILE}" "${FILE}.tmp"; mv "${FILE}.tmp" "${FILE}";

dpkg --force-depends -i ${CASSANDRA_TOOLS_DEB}

rm ${CASSANDRA_TOOLS_DEB}

FILE=/usr/bin/sstablerepairedset

sed -e 's%"x$CLASSPATH" = "x"%true%' -e 's%/../../lib/%/../share/cassandra/lib/%' -e '35 i for jar in `dirname $0`/../share/cassandra/*.jar; do CLASSPATH=$CLASSPATH:$jar; done' ${FILE} > ${FILE}.tmp

mv ${FILE}.tmp ${FILE}; chmod 0555 ${FILE}
